apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-manager-frontend
  labels:
    app: movie-manager-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-manager-frontend
  template:
    metadata:
      labels:
        app: movie-manager-frontend
    spec:
      containers:
        - name: frontend
          image: 163511166008.dkr.ecr.us-east-1.amazonaws.com/movie-manager-frontend:eks-v2
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: movie-manager-frontend
  labels:
    app: movie-manager-frontend
spec:
  selector:
    app: movie-manager-frontend
  ports:
    - name: http
      port: 80        # اللي الـ Ingress هيكلمه
      targetPort: 3000
  type: ClusterIP
